###########################################################################################
#
#  DEV ENVIRONMENT VARIABLES
#
###########################################################################################

_site_root: /~philippe/meeting_summit/statamic/
_site_url: ~philippe/meeting_summit/statamic/