###########################################################################################
#
#  DEV ENVIRONMENT VARIABLES
#
###########################################################################################

_site_root: /meeting_summit/statamic/
_site_url: http://clients.philippe.io/meeting_summit/statamic/